# Generated by Django 6.0.2 on 2026-02-19 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='ads.advertisement'),
        ),
    ]
